<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CHaRT Quarterly Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .client-info {
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 20px;
        }
        .section-title {
            font-weight: bold;
            font-size: 14px;
            margin-bottom: 10px;
        }
        .hours-summary {
            display: flex;
            justify-content: space-between;
            margin-bottom: 15px;
        }
        .hours-item {
            text-align: center;
        }
        .hours-value {
            font-size: 16px;
            font-weight: bold;
        }
        .status-item {
            margin-bottom: 8px;
        }
        .status-label {
            font-weight: bold;
        }
        .journal-entry {
            margin-bottom: 10px;
            padding: 5px;
            border-left: 3px solid #ccc;
        }
        .journal-date {
            font-weight: bold;
        }
        .journal-hours {
            color: #666;
        }
        .attendance-section {
            margin-top: 20px;
        }
        .attendance-item {
            margin-bottom: 5px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>CHaRT Quarterly Report</h1>
        <h2>{{ $client->name }}</h2>
        <p>Q{{ $quarter }} - {{ $year }}</p>
        <p>{{ now()->format('n/j/Y') }}</p>
    </div>

    <div class="client-info">
        <p><strong>Program:</strong> {{ $client->program }}</p>
        <p><strong>Total Hours Allocated:</strong> {{ $client->total_hours }}</p>
    </div>

    <div class="section">
        <div class="section-title">Hours Summary</div>
        <div class="hours-summary">
            <div class="hours-item">
                <div class="hours-value">{{ number_format($total_hours, 2) }}</div>
                <div>Hours Used</div>
            </div>
            <div class="hours-item">
                <div class="hours-value">{{ number_format($hours_remaining, 2) }}</div>
                <div>Hours Remaining</div>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Status</div>
        <div class="status-item">
            <span class="status-label">Established Pattern of Contact:</span>
            {{ $has_established_pattern ? 'Yes' : 'No' }}
        </div>
        <div class="status-item">
            <span class="status-label">On Track for Balanced Use:</span>
            {{ $usage_status === 'balanced' ? 'Yes' : 'No' }}
            @if($usage_status !== 'balanced')
                ({{ $this->getUsageStatusMessage($usage_status) }})
            @endif
        </div>
    </div>

    <div class="section">
        <div class="section-title">Quarterly Activities</div>
        @forelse($journal_entries as $entry)
            <div class="journal-entry">
                <div class="journal-date">{{ $entry->date->format('M j, Y') }}</div>
                <div class="journal-hours">{{ $entry->hours }} hours - {{ ucfirst($entry->category) }}</div>
                @if($entry->client_note)
                    <div>{{ $entry->client_note }}</div>
                @endif
            </div>
        @empty
            <p>No activities recorded for this quarter.</p>
        @endforelse
    </div>

    <div class="attendance-section">
        <div class="section-title">Event Attendance ({{ $year }})</div>
        @php
            $attendanceByEvent = $attendance->groupBy('event');
        @endphp
        @foreach($attendanceByEvent as $event => $attendees)
            <div class="attendance-item">
                <strong>{{ ucfirst($event) }}:</strong> {{ $attendees->count() }} attendees
            </div>
        @endforeach
    </div>

    <div class="footer">
        <p>Generated by CHaRT - Client Hours and Reporting Tool</p>
        <p>Columinate | CBLD Program</p>
    </div>
</body>
</html>
